version: '3.8'

services:
  error-management:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8502:8502"  # Streamlit dashboard
      - "8080:8080"  # API
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
      - AUTO_FIX=1
      - MONITOR_ENABLED=1
      - ERROR_DETECTION_ENABLED=1
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    command: ["./entrypoint.sh"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8502"]
      interval: 30s
      timeout: 10s
      retries: 3
