version: '3.8'

services:
  error-management:
    build:
      context: .
      dockerfile: Dockerfile
    image: error-management-system:latest
    container_name: error-management
    volumes:
      - ${PROJECT_PATH:-./test_project}:/workspace:ro
      - ./certs:/app/certs:ro
    environment:
      - SECURE_MODE=1
      - LOG_LEVEL=INFO
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    ports:
      - "50051:50051"  # gRPC
      - "8080:8080"    # Health/Metrics
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp
    networks:
      - agent-network

  monitoring:
    image: prom/prometheus:latest
    container_name: monitoring
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - error-management
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.28.0.0/16
